version: '3.8'

x-DbLoggin:
  environment:
    &postgres-login
    # the posgress user master password
    POSTGRES_PASSWORD: "password"

    USER_USERNAME: "docker"
    USER_DB_NAME: "docker"
    USER_PASSWORD: "docker"
  
  networks: 
    &postgres-ip
    ipv4_address: "10.20.30.40"



services:
  postgres_db:
    image: postgres

    
    environment: 
      << : *postgres-login
      PGDATA: "/var/lib/postgresql/data/pgdata"

    networks:
      local_network: *postgres-ip


    ports:
      - "5432:5432"

    volumes:
    - type: volume
      source: postgres_db
      target: /var/lib/postgresql/data

    - type: bind
      source: ./docker_files/db_init
      target: /docker-entrypoint-initdb.d



    restart: unless-stopped

  
networks:
  local_network:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8


volumes:
  postgres_db: